#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if nc -z -w 5 localhost "$PORT" >/dev/null 2>&1; then
    su abc -l --command "/usr/local/bin/ampinstmgr --silent ProcessPendingTasks"
    sleep 5
else
    su abc -l --command "/usr/local/bin/ampinstmgr StartBoot"
    sleep 5
fi
