#!/usr/bin/with-contenv bash

dpkg --add-architecture i386

echo "\
    lib32stdc++6 \
    lib32z1 \
    libncurses6:i386 \
    libbz2-1.0:i386 \
    libtinfo6:i386 \
    libcurl3-gnutls:i386 \
    libsdl2-2.0-0:i386" >> /mod-repo-packages-to-install.list
	

